# Generated by Django 5.1.2 on 2024-10-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_order_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_details',
            name='payment_status',
            field=models.CharField(default='pending', max_length=30),
        ),
    ]
